const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require(process.env.SITE_TEST_JSDOM || 'jsdom');
const root=path.resolve(__dirname,'../..');const currentSite=path.basename(path.resolve(__dirname,'..'));
const sites={
'creative-portfolio':['home','work','about','services','photography','journal','contact','privacy','confirmation','project/subbu-coffee','journal/start-with-a-better-question'],
'event-conference':['home','speakers','schedule','my-schedule','tickets','register','sponsors','venue','about','contact','privacy','confirmation','speaker/poluru','session/session-1','sponsor/poluru-labs'],
'financial-advisor':['home','services','calculators','calculator/growth','calculator/retirement','calculator/savings','calculator/education','calculator/loan','advisors','insights','about','contact','privacy','disclosures','service/retirement-planning','advisor/poluru','insight/a-goal-needs-a-time-horizon'],
'crm-sales-dashboard':['overview','leads','contacts','companies','pipeline','opportunities','activities','forecasts','reports','team','settings','privacy','about','leads/lead-2','contacts/contact-0','companies/company-0','opportunities/deal-0','activities/activity-0'],
'crypto-portfolio-dashboard':['overview','holdings','markets','allocation','transactions','performance','watchlist','portfolios','settings','privacy','about','asset/BTC']};
let total=0;
for(const[site,routes]of Object.entries(sites)){if(site!==currentSite)continue;
 const base=path.join(root,site),dom=new JSDOM(fs.readFileSync(path.join(base,'index.html'),'utf8'),{url:'http://localhost:8000/'+site+'/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,d=w.document,errors=[],downloads=[];
 w.addEventListener('error',e=>errors.push(e.error));w.scrollTo=()=>{};w.confirm=()=>true;w.Chart=class{constructor(el,config){assert.ok(config.data.datasets);for(const ds of config.data.datasets)assert.ok(ds.data.every(x=>x===null||Number.isFinite(x)),'Chart contains invalid values');}destroy(){}};w.HTMLDialogElement.prototype.showModal=function(){if(this.open)throw Error('Dialog already open');this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.URL.createObjectURL=()=>'/download';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){downloads.push(this.download)};
 const scripts=[...d.querySelectorAll('script[src]')].map(s=>s.getAttribute('src')).filter(s=>!s.startsWith('https:')&&!s.includes('/vendor/')).map(s=>fs.readFileSync(path.join(base,s),'utf8')).join('\n');
 try{
 w.eval(scripts+'\nwindow.testAPI={render,handleAction,get db(){return typeof db!=="undefined"?db:null},get state(){return typeof state!=="undefined"?state:null},get ui(){return typeof ui!=="undefined"?ui:null}};');
 const api=w.testAPI,nav=r=>{w.location.hash='#/'+r;api.render();assert.ok(d.querySelector('h1'),'Missing heading: '+r);assert.ok(d.querySelector('#app').textContent.length>60,'Empty route: '+r);total++},act=a=>api.handleAction(a),submit=(selector,values)=>{const f=d.querySelector(selector);assert.ok(f,'Missing form '+selector);for(const[k,v]of Object.entries(values)){assert.ok(f.elements.namedItem(k),'Missing '+k);f.elements.namedItem(k).value=v}f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));};
 for(const r of routes)nav(r);
 const linked=new Set();for(const r of routes){nav(r);d.querySelectorAll('#app a[href^="#/"]').forEach(a=>linked.add(a.getAttribute('href').slice(2)))}for(const r of linked){nav(r);assert.ok(!d.querySelector('#app').textContent.includes('This page has moved out of frame.'),'Broken route '+r)}
 nav('missing-page');assert.ok(d.querySelector('#app').textContent.includes('404'));
 if(site==='creative-portfolio'){nav('work');assert.equal(d.querySelectorAll('#projects article').length,12);d.querySelector('#work-search').value='zz-no-match';d.querySelector('#work-search').dispatchEvent(new w.Event('input'));assert.ok(d.querySelector('#projects').textContent.includes('No projects'));act('lightbox:0');assert.ok(d.querySelector('#dialog').open);act('lightbox:1');assert.ok(d.querySelector('#dialog-title').textContent.includes('Subra'));d.querySelector('#dialog').close();nav('journal');assert.equal(d.querySelectorAll('#articles article').length,6);}
 if(site==='event-conference'){nav('schedule');act('bookmark:session-1');act('bookmark:session-2');nav('my-schedule');assert.equal(d.querySelectorAll('.session-conflict').length,2);act('calendar:saved');assert.ok(downloads.includes('converge-schedule.ics'));nav('register');assert.ok(d.querySelector('#order-summary').textContent.includes('$149.00'));d.querySelector('#f-quantity').value='2';d.querySelector('#f-quantity').dispatchEvent(new w.Event('input'));assert.ok(d.querySelector('#order-summary').textContent.includes('$298.00'));}
 if(site==='financial-advisor'){nav('calculator/growth');for(const[k,v]of Object.entries({initial:1000,monthly:100,years:1,rate:0,inflation:0})){const el=d.querySelector('#f-'+k);el.value=v;el.dispatchEvent(new w.Event('input'))}assert.ok(d.querySelector('#calc-summary').textContent.includes('$2,200.00'));act('calc-compare');assert.ok(d.querySelector('#comparison-note').textContent.includes('$2,440.00'));act('calc-save');act('calc-reset');act('calc-load');assert.equal(d.querySelector('#f-initial').value,'1000');nav('calculator/loan');for(const[k,v]of Object.entries({amount:1200,years:1,rate:0})){const el=d.querySelector('#f-'+k);el.value=v;el.dispatchEvent(new w.Event('input'))}assert.ok(d.querySelector('#calc-summary').textContent.includes('$100.00'));}
 if(site==='crm-sales-dashboard'){nav('leads');const old=api.db.leads.length;act('create:leads');submit('#dialog form',{name:'Test Lead',owner:'Poluru',company:'company-0',email:'new@example.com',status:'Qualified',source:'Website',value:12000,notes:'A test qualification'});assert.equal(api.db.leads.length,old+1);const l=api.db.leads.at(-1);act('convert:'+l.id);submit('#dialog form',{opportunity:'yes'});assert.ok(l.converted);const c=api.db.contacts.find(c=>c.email==='new@example.com');assert.ok(c);nav('contacts');act('create:contacts');submit('#dialog form',{name:'Duplicate',email:'new@example.com',company:'company-0'});assert.ok(d.querySelector('#form-error').textContent.includes('already exists'));d.querySelector('#dialog').close();nav('pipeline');act('edit:opportunities:deal-0');submit('#dialog form',{stage:'Closed Lost',lossReason:''});assert.ok(d.querySelector('#form-error').textContent.includes('loss reason'));d.querySelector('#dialog').close();}
 if(site==='crypto-portfolio-dashboard'){nav('transactions');const n=api.db.transactions.length;act('transaction:new');submit('#dialog form',{date:api.db.asOf,type:'Buy',asset:'BTC',quantity:10000,price:68000,fee:0,portfolio:'main'});assert.ok(d.querySelector('#form-error').textContent.includes('Insufficient'));assert.equal(api.db.transactions.length,n);submit('#dialog form',{type:'Deposit',asset:'USD',quantity:1000,price:1,fee:0,portfolio:'main'});assert.equal(api.db.transactions.length,n+1);nav('allocation');submit('#target-form',{BTC:99});assert.ok(d.querySelector('#target-error').textContent.includes('100%'));nav('watchlist');act('alert:new');submit('#dialog form',{asset:'BTC',direction:'Above',price:100});assert.ok(api.db.alerts.some(a=>a.price===100));act('notifications');assert.ok(d.querySelector('#dialog-body').textContent.includes('sample price'));d.querySelector('#dialog').close();}
 assert.equal(errors.length,0,errors.map(String).join('\n'));console.log('PASS',site,linked.size,'linked routes and core interactions');
 }catch(e){console.error('FAIL',site,e.stack);process.exitCode=1}finally{w.close()}
}
console.log('Rendered',total,'routes including linked detail pages.');
